# frozen_string_literal: true

require('darkroom/asset')
require('darkroom/darkroom')
require('darkroom/delegate')
require('darkroom/version')

require('darkroom/delegates/css_delegate')
require('darkroom/delegates/html_delegate')
require('darkroom/delegates/htx_delegate')
require('darkroom/delegates/javascript_delegate')

Darkroom.register('.apng', 'image/apng')
Darkroom.register('.avif', 'image/avif')
Darkroom.register('.css', Darkroom::CSSDelegate)
Darkroom.register('.gif', 'image/gif')
Darkroom.register('.htm', '.html', Darkroom::HTMLDelegate)
Darkroom.register('.htx', Darkroom::HTXDelegate)
Darkroom.register('.ico', 'image/x-icon')
Darkroom.register('.jpg', '.jpeg', 'image/jpeg')
Darkroom.register('.js', Darkroom::JavaScriptDelegate)
Darkroom.register('.json', 'application/json')
Darkroom.register('.png', 'image/png')
Darkroom.register('.svg', 'image/svg+xml')
Darkroom.register('.txt', 'text/plain')
Darkroom.register('.webp', 'image/webp')
Darkroom.register('.woff', 'font/woff')
Darkroom.register('.woff2', 'font/woff2')
